#' @name init_rrtools
#' @title writes .Rprofile
#'
#' @description Working on it...
#'
#' @param path location to create new package. The last component of the path will be used as the package name
#' @param ... list of description values to override default values or add additional values
#' @export

init_rrtools <- function(path, ...){
  # ProjectTemplate file
  header <- c(
    "# This file was generated by a call to 'rrtools::init_rrtools()'.",
    "# The following inputs were received from the Project Template:",
    ""
  )
  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    if(key == "textGH"){
      val <- "secret"
    } else {
      val <- dots[[i]]
    }
    paste0(key, ": ", val)
  })
  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  NAME <- dots[["textName"]]
  EMAIL <- dots[["textEmail"]]
  # is use folder box is checked, select option for directory structure
  if(isTRUE(dots[["checkAnalysis"]])){
    analysis_param  <- dots[["selectAnalysis"]]
    analysis_string <- paste0('rrtools::use_analysis(location = "',analysis_param,'")',collapse='')
  } else {
    analysis_string <- ""
  }
  if(isTRUE(dots[["checkMIT"]])){
    MIT_string <- paste0('devtools::use_mit_license(copyright_holder = "',
                              NAME,'")',collapse='')
  } else {
    MIT_string <- ""
  }
  if(isTRUE(dots[["checkGH"]]) & length(dots[["textGH"]]) > 0){
    GH_token  <- dots[["textGH"]]
    GH_private <- dots[["checkGHPrivate"]]
    GH_string <- paste0('devtools::use_github(auth_token = "',
                         GH_token,'", private = ',
                         GH_private,')',collapse='')
  } else {
    GH_string <- NULL
  }
  if(isTRUE(dots[["checkREADME"]])){
    README_string <- 'rrtools::use_readme_rmd()'
  } else {
    README_string <- NULL
  }

  # build .Rprofile that executes all of the rrtools options
  profile_header <- c(
    '#message("Executing .Rprofile setup")',
    # devtools::funct calls are to try to emulate "build & Clean" in Rstudio, not 100%
    'if (Sys.getenv("RSTUDIO") == "1") local({',
      'on.exit({
          devtools::build()
          devtools::install()
          devtools::load_all()
          file.rename(".Rprofile","Rprofile_init")
      })', # rename .Rprofile
      '## Setup here',
      analysis_string,
      MIT_string,
      README_string,
      GH_string,
    '})'
  )
  rprofile_text <- paste(profile_header, collapse = "\n")

  use_compendium2(path, dots)

  writeLines(contents, con = file.path(path, "ProjectTemplate"))
  writeLines(rprofile_text, con = file.path(path, ".Rprofile"))
}

#' @name use_compendium2
#' @title Creates an R package suitable to use as a research compendium, and
#' switches to the working directory of this new package, ready to work
#'
#' @description This is devtools::create() with an additional step to either start the project in RStudio, or set the working directory to the pkg location, if not using RStudio
#'
#' @param path location to create new package. The last component of the path will be used as the package name
#' @param description list of description values to override default values or add additional values
#' @param check if TRUE, will automatically run \code{devtools::check}
#' @param rstudio create an RStudio project file? (with \code{devtools::use_rstudio})
#' @param quiet if FALSE, the default, prints informative messages
#' @param dots list passed from template UI
#'
#' @importFrom devtools create
#' @importFrom rstudioapi isAvailable
#' @export
use_compendium2 <- function(path, description = getOption("devtools.desc"),
                           check = FALSE, rstudio = TRUE, quiet = FALSE, dots){
  devtools::create(path,
                   description = getOption("devtools.desc"),
                   check,
                   rstudio,
                   quiet)

  message("The package ", path, " has been created \n",
          "Next: \n\n",
          " * Edit the DESCRIPTION file \n",
          " * Use other rrtools functions to add components to the compendium \n",
          " Please wait a moment...  \n")

message("end of compendium2")
}
